version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    volumes:
      - ./selenium-server-4.18.1.jar:/selenium-server.jar  # Mount selenium-server-4.18.1.jar from the host
    command: java -jar /selenium-server.jar -port 4444  # Custom command to start Selenium Server

  firefox-node:
    image: selenium/node-firefox:latest
    container_name: firefox-node
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
