###

GET http://localhost:5000/

###

GET http://localhost:5000/signup

###


POST http://localhost:5000/signup
Content-Type: application/json

{
    "nameUser": "jen",
    "email": "user1@gmail.com",
    "password": "123456",
    "number": "123456789"
}

###
POST http://localhost:5000/404

###
GET http://localhost:5000/public/404
