// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Pages', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Pages', async function() {
    await driver.get("https://devopsproject-v74y.onrender.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css(".nxt-btn")).click()
    await driver.findElement(By.css(".nxt-btn > img")).click()
    await driver.findElement(By.id("card-btn8")).click()
    assert(await driver.switchTo().alert().getText() == "Please Login in system")
    await driver.findElement(By.css(".links-container")).click()
    await driver.findElement(By.id("user-img")).click()
    await driver.findElement(By.id("user-btn")).click()
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("home")).click()
    await driver.findElement(By.id("user-img")).click()
    await driver.findElement(By.xpath("(//button[@id=\'user-btn\'])[2]")).click()
    await driver.findElement(By.id("create")).click()
    await driver.findElement(By.id("home")).click()
    await driver.close()
  })
})
