name: Node.js CI

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium-hub:
        image: selenium/hub:latest
        ports:
          - 4444:4444

      chrome:
        image: selenium/node-chrome:latest
        depends-on:
          - selenium-hub

      firefox:
        image: selenium/node-firefox:latest
        depends-on:
          - selenium-hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: ESLint Check
        run: npm run lint

      - name: Run Selenium Tests on Chrome
        run: node tests/seleniumGrid/test.js chrome

      - name: Run Selenium Tests on Firefox
        run: node tests/seleniumGrid/test.js firefox

      - name: Run Selenium Tests
        run: node tests/seleniumGrid/test.js

      #- name: Run tests
      #  run: npm test

      #- name: SeleniumIDE Register
      #  run: npx mocha tests/seleniumIDE/register.spec.js

      - name: SeleniumIDE Login
        run: npx mocha tests/seleniumIDE/login.spec.js

      - name: SeleniumIDE Pages
        run: npx mocha tests/seleniumIDE/pages.spec.js

      - name: WebDriver Test Cart 
        run: node tests/selenium/cartTest.js

      - name: WebDriver Test Route
        run: node tests/selenium/404Test.js

      - name: WebDriver Test Login
        run: node tests/selenium/loginSeleniumTest.js

      - name: WebDriver Test Register
        run: node tests/selenium/registerSeleniumTest.js

      - name: Build and deploy
        run: |
          # Add any additional build or deploy steps here
          # For example, you can deploy to a server or a cloud platform
          curl "https://api.render.com/deploy/srv-cn8vmhmd3nmc73dfkff0?key=Mkkg-BEOOww"
