name: Node.js CI

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    - name: ESLint Check
      run: npm run lint

      - name: Download and install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

    - name: Download and install ChromeDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/


    #- name: Run tests
    #  run: npm test

    #- name: Run Selenium tests
    #  run: npm run test:selenium
    #- name: SeleniumIDE
    #  run: node tests/seleniumIDE/login.spec.js

    - name: Test Cart
      run: node tests/selenium/cartTest.js

    - name: Test Route
      run: node tests/selenium/404Test.js



    - name: Test Login
      run: node tests/selenium/loginSeleniumTest.js

    - name: Test Regsier
      run: node tests/selenium/registerSeleniumTest.js









    - name: Build and deploy
      run: |
        # Add any additional build or deploy steps here
        # For example, you can deploy to a server or a cloud platform
        curl "https://api.render.com/deploy/srv-cn8vmhmd3nmc73dfkff0?key=Mkkg-BEOOww"