name: Selenium Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/hub:latest
        ports:
          - 4444:4444
        options: --name selenium-hub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install selenium-webdriver

    - name: sleep
      uses: whatnick/wait-action@master
      with:
        time: "15s"

    - name: Run tests
      run: node tests/seleniumGrid/test.js

    - name: Tear down Selenium Grid
      run: docker stop selenium-hub