name: Node.js CI

on:
  push:
    branches:
      - main
      - Home_page_Product_page
      # Add more branches as needed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

    #- name: Run tests
    #  run: npm test

    - name: Build and deploy
      run: |
        # Add any additional build or deploy steps here
        # For example, you can deploy to a server or a cloud platform
        # curl "https://api.render.com/deploy/srv-cn8vmhmd3nmc73dfkff0?key=Mkkg-BEOOww"