name: Functional Tests

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3

jobs:
  run_functional_tests:
    build:
      runs-on: windows-latest
      needs: install_packages

      steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SeleniumIDE Login
        run: npx mocha tests/seleniumIDE/login.spec.js

      - name: SeleniumIDE Pages
        run: npx mocha tests/seleniumIDE/pages.spec.js

      - name: WebDriver Test Cart 
        run: node tests/selenium/cartTest.js

      - name: WebDriver Test Route
        run: node tests/selenium/404Test.js

      - name: WebDriver Test Login
        run: node tests/selenium/loginSeleniumTest.js

      - name: WebDriver Test Register
        run: node tests/selenium/registerSeleniumTest.js

    