name: Functional Tests

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3
      - release_version_1.0

jobs:
  Selenim:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Call Grid Workflow
        uses: ./.github/workflows/Grid.yml