name: Login Packages

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3
      - release_version_1.0

modules:
  nose:
    ignore-unknown-actions: true

execution:
- executor: selenium
  scenario: Login/cart-Selenium
  
  capabilities: 
    browserName: chrome
  hold-for: 20m

- executor: jmeter
  scenario: Login/cart-Http
  concurrency: 20
  ramp-up: 1m
  hold-for: 19m

scenarios:
  Login/cart-Selenium:
    generate-flow-markers: true 
    headless: false
    timeout: 60s
    think-time: 0s
    requests:
    - label: Test
      actions:
      - resizeWindow(1920,919)
      - go(https://devopsproject-v74y.onrender.com/)
      - clickByCSS(button.nxt-btn)
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[contains(text(), "Search")])
      - clickByID(cart-img)
      - clickByXPath(//*[text() = "Buy"])
      - clickByID(cart-img)
      - clickByID(user-img)
      - clickByXPath(//*[text() = "Log In"])
      - clickByXPath(//input[@placeholder = "email"])
      - typeByXPath(//input[@placeholder = "email"]): "Bursov@gmail.com"
      - typeByXPath(//input[@placeholder = "password"]): "12345"
      - keysByXPath(//input[@placeholder = "password"]): KEY_ENTER
      - typeSecretByXPath(//input[@placeholder = "password"]): "12345"
      - clickByXPath(//*[text() = "Log In"])
      - clickByXPath(//input[@placeholder = "password"])
      - typeSecretByXPath(//input[@placeholder = "password"]): "123456"
      - clickByXPath(//*[text() = "Log In"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[contains(text(), "Search")])
      - clickByID(cart-img)
      - clickByXPath(//*[text() = "Buy"])
      - clickByXPath(//*[text() = "Homepage"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByXPath(//*[text() = "Add To Card"])
      - clickByID(cart-img)
      - clickByXPath((//*[text() = "X"])[2])
      - clickByXPath(//*[text() = "Buy"])
      - clickByXPath(//*[text() = "Homepage"])

  Login/cart-Http:
    headers:
      sec-ch-ua: '"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"'
      sec-ch-ua-mobile: '?0'
      sec-ch-ua-platform: '"Windows"'
      User-Agent: >-
        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/124.0.0.0 Safari/537.36
    requests:
      - transaction: Test
        force-parent-sample: false
        do:
          - url: 'https://devopsproject-v74y.onrender.com/pages/login.html'
            method: GET
            label: 'https://devopsproject-v74y.onrender.com/pages/login.html'
            think-time: 0ms
            headers:
              Upgrade-Insecure-Requests: '1'
              Accept: >-
                text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          - url: 'https://devopsproject-v74y.onrender.com/login'
            method: POST
            label: 'https://devopsproject-v74y.onrender.com/login'
            headers:
              Content-Type: application/json
              Accept: '*/*'
            body: '{"email":"Bursov@gmail.com","password":"12345"}'
          - url: 'https://devopsproject-v74y.onrender.com/login'
            method: POST
            label: 'https://devopsproject-v74y.onrender.com/login'
            headers:
              Content-Type: application/json
              Accept: '*/*'
            body: '{"email":"Bursov@gmail.com","password":"123456"}'
          - url: 'https://devopsproject-v74y.onrender.com/'
            method: GET
            label: 'https://devopsproject-v74y.onrender.com/'
            think-time: 488ms
            headers:
              Upgrade-Insecure-Requests: '1'
              Accept: >-
                text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          - url: 'https://devopsproject-v74y.onrender.com/pages/thankPage.html'
            method: GET
            label: 'https://devopsproject-v74y.onrender.com/pages/thankPage.html'
            think-time: 12609ms
            headers:
              Upgrade-Insecure-Requests: '1'
              Accept: >-
                text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          - url: 'https://devopsproject-v74y.onrender.com/pages/index.html'
            method: GET
            label: 'https://devopsproject-v74y.onrender.com/pages/index.html'
            think-time: 2404ms
            headers:
              Upgrade-Insecure-Requests: '1'
              Accept: >-
                text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          - url: 'https://devopsproject-v74y.onrender.com/pages/thankPage.html'
            method: GET
            label: 'https://devopsproject-v74y.onrender.com/pages/thankPage.html'
            think-time: 9445ms
            headers:
              Upgrade-Insecure-Requests: '1'
              Accept: >-
                text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
          - url: 'https://devopsproject-v74y.onrender.com/pages/index.html'
            method: GET
            label: 'https://devopsproject-v74y.onrender.com/pages/index.html'
            think-time: 1846ms
            headers:
              Upgrade-Insecure-Requests: '1'
              Accept: >-
                text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
