name: NoN-Functional Tests

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3
      - release_version_1.0

  workflow_run:
    workflows: ["Install Packages"]
    types:
      - completed

jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    name: Performance Testing
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./tests/NoNFunctionalTest/PerformanceTesting.jmx
          args: ""

      - name: Convert Results to Markdown Table
        run: |
          echo "Test Name, Latency (ms), Response Code" > result.csv
          jq -r '.[] | [.name, .latency, .responseCode] | @csv' result.json >> result.csv
          echo "| Test Name | Latency (ms) | Response Code |" > result.md
          echo "| ----------| -------------| -------------|" >> result.md
          tail -n +2 result.csv | awk -F, '{ printf("| %s | %s | %s |\n", $1, $2, $3) }' >> result.md

      - name: Display Results
        run: cat result.md

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.md
          if-no-files-found: error
