name: NoN-Functional Tests

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3

jobs:
    runs-on: ubuntu-latest
    name: JMeter Test Execution
    
    steps:      
      - name: Checkout
        uses: actions/checkout@v3

      - name: JMeter Test
        uses: QAInsights/PerfAction@v5.6.2
        with:
          test-plan-path: ./FistTest.jmx
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: result.jtl
          if-no-files-found: error