name: ZAP

on:
  push:
    branches:
      - main
      - develop_v_0.2_back
      - feature_0.2_selenium_tests
      - feature_version_3
      - release_version_1.0

permissions:
  issues: write
  contents: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: ZAP Scan
        id: zap_scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://devopsproject-v74y.onrender.com/pages/index.html'

     - name: Parse ZAP Scan Results
        shell: bash
        run: |
          echo "FAIL-NEW: ${{ steps.zap_scan.outputs.fail-new }}"
          echo "FAIL-INPROG: ${{ steps.zap_scan.outputs.fail-inprog }}"
          echo "WARN-NEW: ${{ steps.zap_scan.outputs.warn-new }}"
          echo "WARN-INPROG: ${{ steps.zap_scan.outputs.warn-inprog }}"
          echo "INFO: ${{ steps.zap_scan.outputs.info }}"
          echo "IGNORE: ${{ steps.zap_scan.outputs.ignore }}"
          echo "PASS: ${{ steps.zap_scan.outputs.pass }}"
          
          if [ "${{ steps.zap_scan.outputs.fail-new }}" -ne 0 ] || [ "${{ steps.zap_scan.outputs.fail-inprog }}" -ne 0 ]; then
            echo "Failing build due to ZAP scan failures"
            exit 1
          fi

      - name: Create GitHub Issue for Alerts
        if: ${{ steps.zap_scan.outputs.warn-new != '0' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: ZAP Scan Alerts
          content-filepath: ./zap_scan_report.md
          labels: bug, security

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: ./zap_scan_report.md
